export const LIST_ADD = 'LIST_VIEW_ADD_TO_DO';
export const LIST_DEL = 'LIST_VIEW_DEL_TO_DO';

export const GET_ARTICLE_LIST_INIT = "ARTICLE_INIT";
export const GET_ARTICLE_LIST_LOAD = "ARTICLE_LOAD";
export const GET_ARTICLE_LIST_SUCCESS = "ARTICLE_SUCCESS";
export const GET_ARTICLE_LIST_ERROR = "ARTICLE_ERROR";
